#include <iostream>

using namespace std;

/*
Even Fibonacci numbers

Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int main(int argc, char const *argv[])
{
    int sum = 2, pre = 1, cur = 2, next;
    for (int i = 0; cur < 4000000; i++)
    {
        next = pre + cur;
        pre = cur;
        cur = next;
        if (cur % 2 == 0)
        {
            sum += cur;
        }
    }
    cout << sum << endl;
    return 0;
}